### ISSUE TITLE
Cannot find /dev/twofingtouch

### ISSUE THREAD

**Issue by pg** [pimoroni/raspberry-pi-two-finger-touch#1]
I downloaded this repo and ran the install.sh script. It displays the following error message: `/dev/twofingtouch: No such file or directory`. I guess something isn't getting copied to that spot, but I'm not sure exactly where the issue lies.

**Comment by Robiv8** [comment]
Wy is this issues closed?
I have the same problem.

**Comment by Gadgetoid** [comment]
This is a 4 year old issue on a 5 year old repository that uses 8+ year old code. You'd be better off using the original tool, since I suspect this repository is woefully obsolete - see: https://github.com/Plippo/twofing
